apiVersion: v1
kind: Pod
metadata:
  name: two
  labels:
    id: two
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', "echo $(hostname -i) > /usr/share/nginx/html/index.html"]
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: shared-volume
    emptyDir: {}

