version: '3.9'

services:
  gitlab:
    image: 'gitlab/gitlab-ee:16.0.3-ee.0'
    container_name: gitlab
    restart: always
    hostname: 'kane.sbx.infograb.io'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://kane.sbx.infograb.io'
        gitlab_rails['time_zone'] = 'Asia/Seoul'
        # letsencrypt['enable'] = true
        ### SMTP
        # gitlab_rails['gitlab_shell_ssh_port'] = 8022
        # gitlab_rails['gitlab_email_enabled'] = true
        # gitlab_rails['gitlab_email_display_name'] = '<name>'
        # gitlab_rails['gitlab_email_from'] = 'gitlab@test.com'
        # gitlab_rails['gitlab_email_reply_to'] = 'noreply@test.com'
        # gitlab_rails['smtp_enable'] = true
        # gitlab_rails['smtp_address'] = "<ip>"
        # gitlab_rails['smtp_port'] = 25
        # gitlab_rails['smtp_user_name'] = "<NAME>"
        # gitlab_rails['smtp_password'] = "<PASSWORD>"
        # gitlab_rails['smtp_domain'] = "<DOMAN>"
        # gitlab_rails['smtp_authentication'] = "login" #false
        # gitlab_rails['smtp_enable_starttls_auto'] = true
        # gitlab_rails['smtp_tls'] = false
        # gitlab_rails['smtp_ssl'] = false
        ### NGINX setting
        nginx['redirect_http_to_https'] = true
        nginx['redirect_http_to_https_port'] = 80
        #nginx['ssl_client_certificate'] = "/etc/gitlab/ssl/"
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/kane.sbx.infograb.io/fullchain1.pem"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/kane.sbx.infograb.io/privkey1.pem"
        nginx['ssl_ciphers'] = "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
        nginx['ssl_prefer_server_ciphers'] = 'off'
        nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
        ### Container Registry Settings
        gitlab_rails['registry_enabled'] = true
        registry_external_url 'https://registry-kane.sbx.infograb.io'
        gitlab_rails['registry_host'] = "registry-gitlab.kane.sbx.infograb.io"
        gitlab_rails['registry_path'] = "/var/opt/gitlab/gitlab-rails/shared/registry"
        registry_nginx['redirect_http_to_https'] = true
        registry_nginx['ssl_certificate'] = '/etc/gitlab/ssl/registry-kane.sbx.infograb.io/fullchain1.pem'
        registry_nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/registry-kane.sbx.infograb.io/privkey1.pem'
        ### GitLab Pages Settings
        pages_external_url 'https://pages.kane.sbx.infograb.io'
        gitlab_pages['enable'] = true
        #gitlab_pages['internal_gitlab_server'] = "https://gitlab.test.com"
        gitlab_pages['inplace_chroot'] = true
        ### GitLab Pages NGINX Settings
        pages_nginx['enable'] = true
        pages_nginx['redirect_http_to_https'] = true
        #pages_nginx['ssl_client_certificate'] = ""
        pages_nginx['ssl_certificate'] = "/etc/gitlab/ssl/pages.kane.sbx.infograb.io/fullchain1.pem"
        pages_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/pages.kane.sbx.infograb.io/privkey1.pem"
        pages_nginx['ssl_ciphers'] = 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'
        pages_nginx['ssl_prefer_server_ciphers'] = 'off'
        pages_nginx['ssl_protocols'] = 'TLSv1.2 TLSv1.3'
        ### Prometheus Grafana
        prometheus['enable'] = false
        prometheus['listen_address'] = '0.0.0.0:9090'
        grafana['enable'] = false
        ### EXPORTER
        node_exporter['enable'] = false
        node_exporter['listen_address'] = 'localhost:9100'
        redis_exporter['enable'] = false
        redis_exporter['listen_address'] = 'localhost:9121'
        postgres_exporter['enable'] = false
        postgres_exporter['listen_address'] = 'localhost:9187'
        pgbouncer_exporter['enable'] = false
        pgbouncer_exporter['listen_address'] = 'localhost:9188'
        gitlab_exporter['enable'] = false
        gitlab_exporter['listen_address'] = 'localhost'
        gitlab_exporter['listen_port'] = '9168'
        gitlab_exporter['probe_sidekiq'] = false
        gitlab_exporter['listen_address'] = 'localhost'
        gitlab_exporter['listen_port'] = '9168'
        gitlab_exporter['probe_elasticsearch'] = false
        gitlab_exporter['elasticsearch_url'] = 'http://localhost:9200'
        # gitlab_exporter['elasticsearch_authorization'] = 'Basic <yourbase64encodedcredentials>'
        # gitlab_rails['uploads_object_store_enabled'] = false
        # gitlab_rails['uploads_object_store_remote_directory'] = "reipoc-gitlab-uploads-bucket"
        # gitlab_rails['uploads_object_store_connection'] = {
        #   'provider' => 'AWS',
        #   'region' => 'ap-northeast-2',
        #   'use_iam_profile' => true
        # }
        # gitlab_rails['artifacts_enabled'] = true
        # gitlab_rails['artifacts_object_store_enabled'] = false
        # gitlab_rails['artifacts_object_store_remote_directory'] = "reipoc-gitlab-artifacts-bucket"
        # gitlab_rails['artifacts_object_store_connection'] = {
        #   'provider' => 'AWS',
        #   'region' => 'ap-northeast-2',
        #   'use_iam_profile' => true
        # }
        # gitlab_rails['lfs_object_store_enabled'] = false
        # gitlab_rails['lfs_object_store_remote_directory'] = "reipoc-gitlab-lfs-bucket"
        # gitlab_rails['lfs_object_store_connection'] = {
        #   'provider' => 'AWS',
        #   'region' => 'ap-northeast-2',
        #   'use_iam_profile' => true
        # }
        # gitlab_rails['packages_enabled'] = true
        # gitlab_rails['packages_object_store_enabled'] = false
        # gitlab_rails['packages_object_store_remote_directory'] = "reipoc-gitlab-packages-bucket" 
        # gitlab_rails['packages_object_store_proxy_download'] = false    
        # gitlab_rails['packages_object_store_connection'] = {
        #   'provider' => 'AWS',
        #   'region' => 'ap-northeast-2',
        #   'use_iam_profile' => true
        # }
        # gitlab_rails['pages_object_store_enabled'] = false
        # gitlab_rails['pages_object_store_remote_directory'] = "reipoc-gitlab-pages-bucket"
        # gitlab_rails['pages_object_store_connection'] = {
        #   'provider' => 'AWS',
        #   'region' => 'ap-northeast-2',
        #   'use_iam_profile' => true
        # }
        # registry['storage'] = {
        #  's3' => {
        #    'bucket' => 'reipoc-gitlab-registry-bucket',
        #    'region' => 'ap-northeast-2'
        #  }
        #}
    ports:
      - '8022:22'
      - '80:80'
      - '443:443'
      - '9090:9090'
      - '8093:8093'
    volumes:
      - './config:/etc/gitlab'
      - '/etc/letsencrypt/archive:/etc/gitlab/ssl'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    logging:
      driver: 'json-file'
      options:
        max-size: '200m'
        max-file: '10'