apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: two-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.handongmin.net
    secretName: tls-secret
  rules:
  - host: www.handongmin.net
    http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: nginx-netshoot
            port:
              number: 80
